# Local execution security posture
# For on-box ansible execution (no remote SSH)
---
auth:
  method: network  # Local execution, trust network

ssh:
  port: 22
  permit_root_login: "prohibit-password"
  password_authentication: "no"

sudo:
  nopasswd: true

fail2ban:
  enabled: false

# No additional packages
packages: []
