# SOPS configuration for secrets encryption
# Replace the age public key below with your own key's public key
# Generate a key: age-keygen -o ~/.config/sops/age/keys.txt
# Get public key: grep "public key:" ~/.config/sops/age/keys.txt

creation_rules:
  # Host credentials (Proxmox API tokens, passwords)
  - path_regex: hosts/.*\.tfvars$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Environment configs (tofu tfvars)
  - path_regex: envs/.*/.*\.tfvars$
    age: >-
      age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
