# SOPS configuration for secrets encryption
# Only secrets.yaml is encrypted - all other config files are non-sensitive
#
# Setup:
#   age-keygen -o ~/.config/sops/age/keys.txt
#   Update the 'age' key below with your public key

creation_rules:
  # Single secrets file containing all sensitive values
  - path_regex: secrets\.yaml$
    age: age19g7xlyf8fndus5zzh72w7hlac28fzefwasa2rh6aju74eyh2tq8q2jhc2g
