# Site-wide defaults (non-sensitive)
# Sensitive values are in secrets.yaml

defaults:
  timezone: America/Denver
  domain: local
  datastore: local-zfs
  ssh_user: root
  bridge: vmbr0
  gateway: 10.0.12.1
