# Development security posture
# Permissive settings for development/testing environments
---
auth:
  method: network  # Trust network boundary

ssh:
  port: 22
  permit_root_login: "yes"
  password_authentication: "yes"

sudo:
  nopasswd: true

fail2ban:
  enabled: false

# Additional packages for development
packages:
  - net-tools
  - strace
  - tcpdump
