# Production security posture
# Hardened settings for production environments
---
auth:
  method: node_token  # Per-node unique tokens

ssh:
  port: 22
  permit_root_login: "no"
  password_authentication: "no"

sudo:
  nopasswd: false

fail2ban:
  enabled: true

# No additional packages for prod (minimal attack surface)
packages: []
