# Development environment (node-agnostic template)
# Primary key derived from filename: dev.yaml -> dev
# Node specified at deploy time via: run.sh --host <name>
# Full topology definition added in Phase 5
---
{}
