# Development environment (node-agnostic template)
# Primary key derived from filename: dev.yaml -> dev
# Node specified at deploy time via: run.sh --host <name>
---
# VM ID allocation: base + index (omit for PVE auto-assign)
vmid_base: 10000

vms:
  - name: dev1
    template: test
