#!/bin/bash
# Generate hosts/{hostname}.yaml from system inventory
#
# Usage: ./scripts/host-config.sh [FORCE=1]
#
# Gathers:
#   - Network bridges (vmbr*) with IPs and ports
#   - ZFS pools and devices
#   - SSH access config

set -e

HOSTNAME=$(hostname -s)
OUTPUT_FILE="hosts/${HOSTNAME}.yaml"
FORCE="${FORCE:-0}"

# Check if file exists
if [ -f "$OUTPUT_FILE" ] && [ "$FORCE" != "1" ]; then
    echo "ERROR: $OUTPUT_FILE already exists. Use FORCE=1 to overwrite." >&2
    exit 1
fi

# Warn if not root
if [ "$(id -u)" != "0" ]; then
    echo "WARNING: Not running as root. Some information may be incomplete." >&2
fi

# Start YAML output
cat <<EOF
# Auto-generated by: make host-config
# Host: $HOSTNAME
# Date: $(date -Iseconds)

host: $HOSTNAME

network:
  interfaces:
EOF

# Get bridges and their config
for bridge in $(ip -j link show type bridge 2>/dev/null | python3 -c "import sys,json; [print(x['ifname']) for x in json.load(sys.stdin)]" 2>/dev/null || true); do
    # Get IP address for this bridge
    ip_addr=$(ip -j addr show dev "$bridge" 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for iface in data:
    for addr in iface.get('addr_info', []):
        if addr.get('family') == 'inet':
            print(f\"{addr['local']}/{addr['prefixlen']}\")
            break
" 2>/dev/null || true)

    # Get bridge ports
    ports=$(bridge link show 2>/dev/null | grep "master $bridge" | awk '{print $2}' | sed 's/:$//' | tr '\n' ',' | sed 's/,$//' || true)

    # Get gateway if this bridge has the default route
    gateway=$(ip -j route show default 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
for route in data:
    if route.get('dev') == '$bridge':
        print(route.get('gateway', ''))
        break
" 2>/dev/null || true)

    echo "    $bridge:"
    echo "      type: bridge"
    if [ -n "$ports" ]; then
        echo "      ports: [${ports}]"
    else
        echo "      ports: []"
    fi
    if [ -n "$ip_addr" ]; then
        echo "      address: $ip_addr"
    fi
    if [ -n "$gateway" ]; then
        echo "      gateway: $gateway"
    fi
done

# ZFS pools
if command -v zpool >/dev/null 2>&1; then
    pools=$(zpool list -H -o name 2>/dev/null || true)
    if [ -n "$pools" ]; then
        echo ""
        echo "storage:"
        echo "  zfs_pools:"
        for pool in $pools; do
            echo "    - name: $pool"
            # Get devices for this pool (simplified - just top-level vdevs)
            devices=$(zpool list -vH "$pool" 2>/dev/null | awk 'NR>1 && $1 !~ /^(mirror|raidz|spare|log|cache|special)/ {print $1}' | tr '\n' ',' | sed 's/,$//' || true)
            if [ -n "$devices" ]; then
                echo "      devices: [${devices}]"
            else
                echo "      devices: []"
            fi
        done
    fi
fi

# Access section
echo ""
echo "# Timezone inherited from site.yaml (uncomment to override)"
echo "# timezone: $(cat /etc/timezone 2>/dev/null || echo 'UTC')"
echo ""
echo "access:"
echo "  ssh_user: root"
echo "  authorized_keys: []  # TODO: add key references from secrets.ssh_keys"
