#!/bin/bash
# Generate nodes/{hostname}.yaml from PVE system info
#
# Usage: ./scripts/node-config.sh [FORCE=1]
#
# Requires Proxmox VE to be installed.
#
# Gathers:
#   - API endpoint (https://{fqdn}:8006)
#   - Node name
#   - Default datastore

set -e

HOSTNAME=$(hostname -s)
FQDN=$(hostname -f)
OUTPUT_FILE="nodes/${HOSTNAME}.yaml"
FORCE="${FORCE:-0}"

# Check if PVE is installed
if ! command -v pvesh >/dev/null 2>&1; then
    echo "ERROR: Proxmox VE not detected (pvesh not found)." >&2
    echo "This command requires PVE to be installed." >&2
    exit 1
fi

# Check if file exists
if [ -f "$OUTPUT_FILE" ] && [ "$FORCE" != "1" ]; then
    echo "ERROR: $OUTPUT_FILE already exists. Use FORCE=1 to overwrite." >&2
    exit 1
fi

# Determine datastore (prefer local-zfs, fallback to local)
if command -v zpool >/dev/null 2>&1 && zpool list -H -o name 2>/dev/null | grep -q .; then
    DATASTORE="local-zfs"
else
    DATASTORE="local"
fi

# Try to get a better datastore from pvesm
if command -v pvesm >/dev/null 2>&1; then
    # Get first storage that can hold images
    detected=$(pvesm status --content images 2>/dev/null | awk 'NR>1 && $2=="active" {print $1; exit}' || true)
    if [ -n "$detected" ]; then
        DATASTORE="$detected"
    fi
fi

# Generate YAML output
cat <<EOF
# Auto-generated by: make node-config
# Node: $HOSTNAME
# Date: $(date -Iseconds)

node: $HOSTNAME
host: $HOSTNAME              # FK -> hosts/$HOSTNAME.yaml
api_endpoint: https://${FQDN}:8006
api_token: $HOSTNAME         # FK -> secrets.api_tokens (manual setup required)
datastore: $DATASTORE
EOF
