# General-purpose VM specification
# Debian endpoint: packages, user with sudo, timezone
---
schema_version: 1

access:
  posture: dev
  users:
    - name: homestak
      sudo: true

platform:
  packages:
    - htop
    - curl

config:
  timezone: America/Denver
